name: Create Zip
on:
  push:
    tags:
    - '*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Archive Release
      uses: thedoctor0/zip-release@master
      with:
        filename: 'Modpack.zip'
        exclusions: '*.git* *.md'
    - name: Upload Release
      uses: ncipollo/release-action@v1
      with:
        allowUpdates: true
        artifacts: "Modpack.zip"
        token: ${{ secrets.GITHUB_TOKEN }}
